version: '3.9'

services:
  minhaapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minhaapi
    ports:
      - "8080:8080"
    environment:
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_USE_POLLING_FILE_WATCHER=true
    restart: always
